---
title: 'POLI 168 Group Project: Background, Data, and Research'
author: "Professor Haney Hong & TA Keng-Chi Chang"
date: "2019-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 5: Energy & Water
*Should the California WaterFix project be one or two tunnels or canceled altogether?*

### Background and Data
- https://californiawaterfix.com/
- https://en.wikipedia.org/wiki/California_State_Water_Project
- https://www.energy.ca.gov/almanac/renewables_data/hydro/
- https://data.ca.gov/group/california-department-water-resources
- https://ca.water.usgs.gov/data/
- https://waterdata.usgs.gov/ca/nwis/rt

### Research
- [Economic Analysis of Stage I of the California WaterFix](https://www.dropbox.com/s/kutkxzpnh8rxfpl/Economic%20Analysis%20of%20Stage%20I%20of%20the%20California%20WaterFix.pdf?dl=0)
- [Review of "Economic Analysis of Stage I of the California WaterFix"](https://www.dropbox.com/s/ll5n36agnn4j8hx/Review%20of%20%22Economic%20Analysis%20of%20Stage%20I%20of%20the%20California%20WaterFix%22.pdf?dl=0)
- [Benefit-Cost Analysis of The California WaterFix](https://www.dropbox.com/s/0z78kib86fordg8/Benefit-Cost%20Analysis%20of%20The%20California%20WaterFix.pdf?dl=0)
- [Effects of the proposed California WaterFix North Delta Diversion on flow reversals and entrainment of juvenile Chinook salmon into Georgiana Slough and the Delta Cross Channel, northern California](https://www.dropbox.com/s/rkvhstzztylb6h4/Effects%20of%20the%20proposed%20California%20WaterFix%20North%20Delta%20Diversion%20on%20flow%20reversals%20and%20entrainment%20of%20juvenile%20Chinook%20salmon.pdf?dl=0)

## Week 6: Education
*Should the California Local Control Funding Formula be changed, and if so, how?*

### Background and Data
- https://www.cde.ca.gov/fg/aa/lc/
- https://www.cde.ca.gov/fg/aa/lc/lcffoverview.asp
- https://www.cde.ca.gov/fg/aa/lc/lcfffaq.asp
- https://www.cde.ca.gov/ds/
- https://dq.cde.ca.gov/dataquest/
- https://www.ed-data.org

### Research
- [The Local Control Funding Formula (LCFF): What Have We Learned After Four Years of Implementation?](https://www.dropbox.com/s/zyzk3152ow1sxmw/The%20Local%20Control%20Funding%20Formula%20%28LCFF%29%20-%20What%20Have%20We%20Learned%20After%20Four%20Years%20of%20Implementation%3F.pdf?dl=0)
- [In the Era of the Local Control Funding Formula: The Shifting Role of California’s Chief Business Officers](https://www.dropbox.com/s/jieyqsbqdx0k8ti/In%20the%20Era%20of%20the%20Local%20Control%20Funding%20Formula%20-%20The%20Shifting%20Role%20of%20California%E2%80%99s%20Chief%20Business%20Officers.pdf?dl=0)
- [Taking stock of stakeholder engagement in California’s Local Control Funding Formula: What can we learn from the past four years to guide next steps?](https://www.dropbox.com/s/zq223tifjju12d4/Taking%20stock%20of%20stakeholder%20engagement%20in%20California%E2%80%99s%20Local%20Control%20Funding%20Formula%20-%20What%20can%20we%20learn%20from%20the%20past%20four%20years%20to%20guide%20next%20steps%3F.pdf?dl=0)
- [Principals' Perceptions: Implementing The Local Control Funding Formula](https://www.dropbox.com/s/b8fj1epss1qj09k/Principals%27%20Perceptions%20-%20Implementing%20The%20Local%20Control%20Funding%20Formula.pdf?dl=0)

## Week 7: Housing & Urban Planning
*Should California repeal the Costa-Hawkins Act and permit municipalities the ability to enact more “rent control” or “rent stabilization” measures?*

### Background and Data
- https://en.wikipedia.org/wiki/Costa–Hawkins_Rental_Housing_Act
- https://www.zillow.com/ca/home-values/
- https://factfinder.census.gov/bkmk/table/1.0/en/ACS/17_5YR/DP04/
- https://www.deptofnumbers.com/rent/california/
- https://www.car.org/marketdata/data/
- https://www.census.gov/data-tools/demo/rhfs/rhfs.html
- https://www.kaggle.com/camnugent/california-housing-prices

### Research
- [The Effects of Rent Control Expansion on Tenants, Landlords, and Inequality: Evidence from San Francisco](https://www.dropbox.com/s/pofleyvug6dgdw3/The%20Effects%20of%20Rent%20Control%20Expansion%20on%20Tenants%2C%20Landlords%2C%20and%20Inequality%20-%20Evidence%20from%20San%20Francisco.pdf?dl=0)
- [The Case for Preserving Costa-Hawkins: The Potential Impacts of Rent Control on Single Family Homes](https://www.dropbox.com/s/ecv0biz51ubds23/The%20Case%20for%20Preserving%20Costa-Hawkins%20-%20The%20Potential%20Impacts%20of%20Rent%20Control%20on%20Single%20Family%20Homes.pdf?dl=0)
- [Opening the Door for Rent Control: Toward a Comprehensive Approach to Protecting California's Renters](https://www.dropbox.com/s/909znymk0ojif2a/Opening%20the%20Door%20for%20Rent%20Control-Toward%20a%20Comprehensive%20Approach%20to%20Protecting%20California%27s%20Renters.pdf?dl=0)
- [Rent Matters: What are the Impacts of Rent Stabilization Measures?](https://www.dropbox.com/s/x3kgb59pb2g8dnt/Rent%20Matters%20-%20What%20are%20the%20Impacts%20of%20Rent%20Stabilization%20Measures%3F.pdf?dl=0)

## Week 8: Transportation & Infrastructure
*Should California continue or cancel its pursuit of a high-speed rail project?*

### Background and Data
- http://www.hsr.ca.gov
- https://en.wikipedia.org/wiki/California_High-Speed_Rail
- http://www.hsr.ca.gov/docs/about/ridership/ridership_revenue_source_doc5.pdf
- http://www.dot.ca.gov/trafficops/census/
- http://www.dot.ca.gov/hq/tsip/gis/datalibrary/
- https://data.ca.gov/dataset/caltrans-traffic-volumes

### Research
- [High-Speed Rail and Sustainability](https://www.dropbox.com/s/mn2xwckfgzqut3c/High-Speed%20Rail%20and%20Sustainability.pdf?dl=0)
- [Cost-effectiveness of reductions in greenhouse gas emissions from High-Speed Rail and urban transportation projects in California](https://www.dropbox.com/s/4x6w2jkxp2u2xm9/Cost-effectiveness%20of%20reductions%20in%20greenhouse%20gas%20emissions%20from%20High-Speed%20Rail%20and%20urban%20transportation%20projects%20in%20California.pdf?dl=0)
- [Measuring the Economic Impact of High Speed Rail Construction for California and the Central Valley Region](https://www.dropbox.com/s/cr6qbstsn5rge16/Measuring%20the%20Economic%20Impact%20of%20High%20Speed%20Rail%20Construction%20for%20California%20and%20the%20Central%20Valley%20Region.pdf?dl=0)
- [Life-cycle assessment of high-speed rail: the case of California](https://www.dropbox.com/s/ks0rqad3pkphd79/Life-cycle%20assessment%20of%20high-speed%20rail%20-%20he%20case%20of%20California.pdf?dl=0)
